# The URL the site will be built for
base_url = "https://lfglance.dev"
theme = "hook"
title = "Lance does tech stuff"
description = "this is my personal site for shits and giggles."
compile_sass = false
build_search_index = true

[markdown]
highlight_code = true

[extra]
author = "Lance Allen"
github = "https://github.com/lfglance"
twitter = "lfglance"
email = "lfglance24@gmail.com"
title_separator = "|"
title_addition = ""
timeformat = "%Y-%m-%d %H:%M:%S" # 2021-05-01 09:19:42
timezone = "UTC"
edit_page = false
